### ISSUE TITLE
Add token_validity_units or ability to set expire for each individual token (access/id)

### ISSUE THREAD

**Issue by ndanl** [mineiros-io/terraform-aws-cognito-user-pool#45]
Currently only refresh tokens are available to set, is it possible to update the code and refresh access and id tokens as well? or use token_validity_units?

**Comment by soerenmartius** [comment]
Hi @ndanl , 

Thanks for reporting this. We will discuss this internally and come back to you about this asap.

Have a good day!

**Comment by soerenmartius** [comment]
Hi @ndanl,

`token_validity_units` has only been added to the AWS provider in version [3.32.0](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md#3320-march-12-2021) which was released in March earlier this year. When we released the latest version of this module, we only added support for version `3.19` since it was the most recent released version by the time.

Since we're currently focussing on releasing new open-source modules and none of our clients has been requested to add `token_validity_units`, we can unfortunately not consider it right away but we will put it in our roadmap (no ETA so far). 

In the meantime, you can always open a PR and contribute to this module - we welcome that.

Again, thanks for reporting this.
